### PR TITLE
make shield-agent to accept custom binary paths

### PR DESCRIPTION
**Pull request by karampok**
Hi, 
we have a modified version of the S3 plugin to support our custom S3 storage, and we need to collocate two bosh releases. For that reason we need the config file of the shield-agent not to static, and recognise binaries in other location.

### CODE REVIEW

**Comment by geofffranks** [comment]
What changes did you make to the s3 plugin?   Is there merit in submitting a PR with them?

**Comment by karampok** [comment]
We require the latest version of minio-go, and we might have to make the same changes as in scality (multiparts size or disable multiparts!) but different signature and there is somewhere we must  put true 
```
(343         s3Client, err = minio.NewV2(s3.Host, s3.AccessKey, s3.SecretKey, true))
```
we still testing, we do not have something stable. I do not think it has value for you.

In the future, we plan to have plugins for services like mongodb, elasticsearch. Then for sure we will make a PR.

**Comment by jhunt** [comment]
Does it make sense to re-merge the scality and s3 plugins with some better options?  I.e. give plugin writers the ability to disable multipart, or force multipart sizing?  @thomasmmitchell / @geofffranks ?

**Comment by thomasmmitchell** [comment]
I don't necessarily like the idea of the configuration bloat falling to the user.

**Comment by jhunt** [comment]
Even with sane defaults?

**Comment by thomasmmitchell** [comment]
With sane defaults, sure... Deleting the scality plugin is going to break a few active deployments on an upgrade though...

**Comment by thomasmmitchell** [comment]
@karampok What is the quality of this version of minio that makes it work with your 's3' storage?
Also, is this version a fork or a recent update?

**Comment by karampok** [comment]
We have not identified the quality of the minio (is the latest btw), and we still need to test further with large sizes before we say it works. Therefore we are not in the case to "merge the scality and s3 plugins with some better options", rather than to modify it in not generic way. 
This change will allow to be flexible in case we have to use different binaries, which can be handy also during testing.

**Comment by karampok** [comment]
Code-wise are the changes ok? Do we make another change to be complete?

**Comment by geofffranks** [comment]
Nope this is cool otherwise. Thanks!

**Comment by geofffranks** [comment]
@karampok this is be included in the v6.3.1 boshrelease.

**Pull request merged**
