### PR TITLE
allow to use the WEB UI via http

### PR DESCRIPTION
**Pull request by gogolok**

### CODE REVIEW

**Comment by jhunt** [comment]
I'm not comfortable with allowing unencrypted traffic to the SHIELD Web UI (and, by extension, disabling TLS on the API).  The API handles sensitive data about the targets and stores, including usernames, passwords, keys, etc.

What is your use case for _not_ using SSL/TLS?

**Comment by MatthiasWinzeler** [comment]
We'd like to terminate SSL on our hardware loadbalancer where we have proper certificate management, hardware acceleration etc.

**Comment by MatthiasWinzeler** [comment]
hi guys - any update on this?

**Comment by jhunt** [comment]
This got taken care of independently in https://github.com/starkandwayne/shield-boshrelease/commit/900edacf49c617c8907efd9256fb89ac079846fa

**Pull request closed without merging**
