### PR TITLE
Don't use -%> since it's not supported by bosh create-env

### PR DESCRIPTION
**Pull request by rkoster**

### CODE REVIEW

**Comment by rkoster** [comment]
will look into the failure and add some template tests.

**Comment by jhunt** [comment]
My guess is that the go stdlib can't deal with the newline at the end of the keyfile, which is why we were using `-%>` in the first place.

Does the BOSH CLI team know that hyphen-trimming isn't supported by `create-env`?  If not, perhaps we should file an issue there instead.  If so, we should try to get some focus on the issue so that it gets resolved upstream.

**Comment by rkoster** [comment]
have created: https://github.com/cloudfoundry/bosh-cli/issues/381

**Comment by rkoster** [comment]
@jhunt is there use case for not specifying an agent.key?

**Comment by rkoster** [comment]
@jhunt any preference on where to run the release unit tests?

**Comment by jhunt** [comment]
Let's just wait until upstream the bosh-cli fix is incorporated.

**Comment by lnguyen** [comment]
:+1: I have this issue now

**Comment by jhunt** [comment]
Fixed in c7b330c

**Pull request closed without merging**
